# frozen_string_literal: true

source "https://rubygems.org"

# Runtime + native-extension build deps come from the gemspec.
gemspec

group :development do
  gem "rake", "~> 13.0"
  gem "rake-compiler", "~> 1.2"
  gem "minitest", "~> 5.0"
end
